//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bewallwpf.WebServicePoxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServicePoxy.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name GetWeatherResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeather", ReplyAction="*")]
        bewallwpf.WebServicePoxy.GetWeatherResponse GetWeather(bewallwpf.WebServicePoxy.GetWeatherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeather", ReplyAction="*")]
        System.Threading.Tasks.Task<bewallwpf.WebServicePoxy.GetWeatherResponse> GetWeatherAsync(bewallwpf.WebServicePoxy.GetWeatherRequest request);
        
        // CODEGEN: Generating message contract since element name GetNewsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNews", ReplyAction="*")]
        bewallwpf.WebServicePoxy.GetNewsResponse GetNews(bewallwpf.WebServicePoxy.GetNewsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNews", ReplyAction="*")]
        System.Threading.Tasks.Task<bewallwpf.WebServicePoxy.GetNewsResponse> GetNewsAsync(bewallwpf.WebServicePoxy.GetNewsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAd", ReplyAction="*")]
        bewallwpf.WebServicePoxy.GetAdResponse GetAd(bewallwpf.WebServicePoxy.GetAdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAd", ReplyAction="*")]
        System.Threading.Tasks.Task<bewallwpf.WebServicePoxy.GetAdResponse> GetAdAsync(bewallwpf.WebServicePoxy.GetAdRequest request);
        
        // CODEGEN: Generating message contract since element name GetPiesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPies", ReplyAction="*")]
        bewallwpf.WebServicePoxy.GetPiesResponse GetPies(bewallwpf.WebServicePoxy.GetPiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPies", ReplyAction="*")]
        System.Threading.Tasks.Task<bewallwpf.WebServicePoxy.GetPiesResponse> GetPiesAsync(bewallwpf.WebServicePoxy.GetPiesRequest request);
        
        // CODEGEN: Generating message contract since element name GetBarOrLinesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBarOrLines", ReplyAction="*")]
        bewallwpf.WebServicePoxy.GetBarOrLinesResponse GetBarOrLines(bewallwpf.WebServicePoxy.GetBarOrLinesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBarOrLines", ReplyAction="*")]
        System.Threading.Tasks.Task<bewallwpf.WebServicePoxy.GetBarOrLinesResponse> GetBarOrLinesAsync(bewallwpf.WebServicePoxy.GetBarOrLinesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAppInfoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAppInfo", ReplyAction="*")]
        bewallwpf.WebServicePoxy.GetAppInfoResponse GetAppInfo(bewallwpf.WebServicePoxy.GetAppInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAppInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<bewallwpf.WebServicePoxy.GetAppInfoResponse> GetAppInfoAsync(bewallwpf.WebServicePoxy.GetAppInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeatherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeather", Namespace="http://tempuri.org/", Order=0)]
        public bewallwpf.WebServicePoxy.GetWeatherRequestBody Body;
        
        public GetWeatherRequest() {
        }
        
        public GetWeatherRequest(bewallwpf.WebServicePoxy.GetWeatherRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetWeatherRequestBody {
        
        public GetWeatherRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeatherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeatherResponse", Namespace="http://tempuri.org/", Order=0)]
        public bewallwpf.WebServicePoxy.GetWeatherResponseBody Body;
        
        public GetWeatherResponse() {
        }
        
        public GetWeatherResponse(bewallwpf.WebServicePoxy.GetWeatherResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeatherResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetWeatherResult;
        
        public GetWeatherResponseBody() {
        }
        
        public GetWeatherResponseBody(string GetWeatherResult) {
            this.GetWeatherResult = GetWeatherResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNews", Namespace="http://tempuri.org/", Order=0)]
        public bewallwpf.WebServicePoxy.GetNewsRequestBody Body;
        
        public GetNewsRequest() {
        }
        
        public GetNewsRequest(bewallwpf.WebServicePoxy.GetNewsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNewsRequestBody {
        
        public GetNewsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewsResponse", Namespace="http://tempuri.org/", Order=0)]
        public bewallwpf.WebServicePoxy.GetNewsResponseBody Body;
        
        public GetNewsResponse() {
        }
        
        public GetNewsResponse(bewallwpf.WebServicePoxy.GetNewsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNewsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNewsResult;
        
        public GetNewsResponseBody() {
        }
        
        public GetNewsResponseBody(string GetNewsResult) {
            this.GetNewsResult = GetNewsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAd", Namespace="http://tempuri.org/", Order=0)]
        public bewallwpf.WebServicePoxy.GetAdRequestBody Body;
        
        public GetAdRequest() {
        }
        
        public GetAdRequest(bewallwpf.WebServicePoxy.GetAdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAdRequestBody {
        
        public GetAdRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAdResponse", Namespace="http://tempuri.org/", Order=0)]
        public bewallwpf.WebServicePoxy.GetAdResponseBody Body;
        
        public GetAdResponse() {
        }
        
        public GetAdResponse(bewallwpf.WebServicePoxy.GetAdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAdResult;
        
        public GetAdResponseBody() {
        }
        
        public GetAdResponseBody(string GetAdResult) {
            this.GetAdResult = GetAdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPies", Namespace="http://tempuri.org/", Order=0)]
        public bewallwpf.WebServicePoxy.GetPiesRequestBody Body;
        
        public GetPiesRequest() {
        }
        
        public GetPiesRequest(bewallwpf.WebServicePoxy.GetPiesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPiesRequestBody {
        
        public GetPiesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPiesResponse", Namespace="http://tempuri.org/", Order=0)]
        public bewallwpf.WebServicePoxy.GetPiesResponseBody Body;
        
        public GetPiesResponse() {
        }
        
        public GetPiesResponse(bewallwpf.WebServicePoxy.GetPiesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPiesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPiesResult;
        
        public GetPiesResponseBody() {
        }
        
        public GetPiesResponseBody(string GetPiesResult) {
            this.GetPiesResult = GetPiesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBarOrLinesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBarOrLines", Namespace="http://tempuri.org/", Order=0)]
        public bewallwpf.WebServicePoxy.GetBarOrLinesRequestBody Body;
        
        public GetBarOrLinesRequest() {
        }
        
        public GetBarOrLinesRequest(bewallwpf.WebServicePoxy.GetBarOrLinesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBarOrLinesRequestBody {
        
        public GetBarOrLinesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBarOrLinesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBarOrLinesResponse", Namespace="http://tempuri.org/", Order=0)]
        public bewallwpf.WebServicePoxy.GetBarOrLinesResponseBody Body;
        
        public GetBarOrLinesResponse() {
        }
        
        public GetBarOrLinesResponse(bewallwpf.WebServicePoxy.GetBarOrLinesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBarOrLinesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBarOrLinesResult;
        
        public GetBarOrLinesResponseBody() {
        }
        
        public GetBarOrLinesResponseBody(string GetBarOrLinesResult) {
            this.GetBarOrLinesResult = GetBarOrLinesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAppInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAppInfo", Namespace="http://tempuri.org/", Order=0)]
        public bewallwpf.WebServicePoxy.GetAppInfoRequestBody Body;
        
        public GetAppInfoRequest() {
        }
        
        public GetAppInfoRequest(bewallwpf.WebServicePoxy.GetAppInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAppInfoRequestBody {
        
        public GetAppInfoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAppInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAppInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public bewallwpf.WebServicePoxy.GetAppInfoResponseBody Body;
        
        public GetAppInfoResponse() {
        }
        
        public GetAppInfoResponse(bewallwpf.WebServicePoxy.GetAppInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAppInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAppInfoResult;
        
        public GetAppInfoResponseBody() {
        }
        
        public GetAppInfoResponseBody(string GetAppInfoResult) {
            this.GetAppInfoResult = GetAppInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : bewallwpf.WebServicePoxy.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<bewallwpf.WebServicePoxy.WebService1Soap>, bewallwpf.WebServicePoxy.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bewallwpf.WebServicePoxy.GetWeatherResponse bewallwpf.WebServicePoxy.WebService1Soap.GetWeather(bewallwpf.WebServicePoxy.GetWeatherRequest request) {
            return base.Channel.GetWeather(request);
        }
        
        public string GetWeather() {
            bewallwpf.WebServicePoxy.GetWeatherRequest inValue = new bewallwpf.WebServicePoxy.GetWeatherRequest();
            inValue.Body = new bewallwpf.WebServicePoxy.GetWeatherRequestBody();
            bewallwpf.WebServicePoxy.GetWeatherResponse retVal = ((bewallwpf.WebServicePoxy.WebService1Soap)(this)).GetWeather(inValue);
            return retVal.Body.GetWeatherResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bewallwpf.WebServicePoxy.GetWeatherResponse> bewallwpf.WebServicePoxy.WebService1Soap.GetWeatherAsync(bewallwpf.WebServicePoxy.GetWeatherRequest request) {
            return base.Channel.GetWeatherAsync(request);
        }
        
        public System.Threading.Tasks.Task<bewallwpf.WebServicePoxy.GetWeatherResponse> GetWeatherAsync() {
            bewallwpf.WebServicePoxy.GetWeatherRequest inValue = new bewallwpf.WebServicePoxy.GetWeatherRequest();
            inValue.Body = new bewallwpf.WebServicePoxy.GetWeatherRequestBody();
            return ((bewallwpf.WebServicePoxy.WebService1Soap)(this)).GetWeatherAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bewallwpf.WebServicePoxy.GetNewsResponse bewallwpf.WebServicePoxy.WebService1Soap.GetNews(bewallwpf.WebServicePoxy.GetNewsRequest request) {
            return base.Channel.GetNews(request);
        }
        
        public string GetNews() {
            bewallwpf.WebServicePoxy.GetNewsRequest inValue = new bewallwpf.WebServicePoxy.GetNewsRequest();
            inValue.Body = new bewallwpf.WebServicePoxy.GetNewsRequestBody();
            bewallwpf.WebServicePoxy.GetNewsResponse retVal = ((bewallwpf.WebServicePoxy.WebService1Soap)(this)).GetNews(inValue);
            return retVal.Body.GetNewsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bewallwpf.WebServicePoxy.GetNewsResponse> bewallwpf.WebServicePoxy.WebService1Soap.GetNewsAsync(bewallwpf.WebServicePoxy.GetNewsRequest request) {
            return base.Channel.GetNewsAsync(request);
        }
        
        public System.Threading.Tasks.Task<bewallwpf.WebServicePoxy.GetNewsResponse> GetNewsAsync() {
            bewallwpf.WebServicePoxy.GetNewsRequest inValue = new bewallwpf.WebServicePoxy.GetNewsRequest();
            inValue.Body = new bewallwpf.WebServicePoxy.GetNewsRequestBody();
            return ((bewallwpf.WebServicePoxy.WebService1Soap)(this)).GetNewsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bewallwpf.WebServicePoxy.GetAdResponse bewallwpf.WebServicePoxy.WebService1Soap.GetAd(bewallwpf.WebServicePoxy.GetAdRequest request) {
            return base.Channel.GetAd(request);
        }
        
        public string GetAd() {
            bewallwpf.WebServicePoxy.GetAdRequest inValue = new bewallwpf.WebServicePoxy.GetAdRequest();
            inValue.Body = new bewallwpf.WebServicePoxy.GetAdRequestBody();
            bewallwpf.WebServicePoxy.GetAdResponse retVal = ((bewallwpf.WebServicePoxy.WebService1Soap)(this)).GetAd(inValue);
            return retVal.Body.GetAdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bewallwpf.WebServicePoxy.GetAdResponse> bewallwpf.WebServicePoxy.WebService1Soap.GetAdAsync(bewallwpf.WebServicePoxy.GetAdRequest request) {
            return base.Channel.GetAdAsync(request);
        }
        
        public System.Threading.Tasks.Task<bewallwpf.WebServicePoxy.GetAdResponse> GetAdAsync() {
            bewallwpf.WebServicePoxy.GetAdRequest inValue = new bewallwpf.WebServicePoxy.GetAdRequest();
            inValue.Body = new bewallwpf.WebServicePoxy.GetAdRequestBody();
            return ((bewallwpf.WebServicePoxy.WebService1Soap)(this)).GetAdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bewallwpf.WebServicePoxy.GetPiesResponse bewallwpf.WebServicePoxy.WebService1Soap.GetPies(bewallwpf.WebServicePoxy.GetPiesRequest request) {
            return base.Channel.GetPies(request);
        }
        
        public string GetPies() {
            bewallwpf.WebServicePoxy.GetPiesRequest inValue = new bewallwpf.WebServicePoxy.GetPiesRequest();
            inValue.Body = new bewallwpf.WebServicePoxy.GetPiesRequestBody();
            bewallwpf.WebServicePoxy.GetPiesResponse retVal = ((bewallwpf.WebServicePoxy.WebService1Soap)(this)).GetPies(inValue);
            return retVal.Body.GetPiesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bewallwpf.WebServicePoxy.GetPiesResponse> bewallwpf.WebServicePoxy.WebService1Soap.GetPiesAsync(bewallwpf.WebServicePoxy.GetPiesRequest request) {
            return base.Channel.GetPiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<bewallwpf.WebServicePoxy.GetPiesResponse> GetPiesAsync() {
            bewallwpf.WebServicePoxy.GetPiesRequest inValue = new bewallwpf.WebServicePoxy.GetPiesRequest();
            inValue.Body = new bewallwpf.WebServicePoxy.GetPiesRequestBody();
            return ((bewallwpf.WebServicePoxy.WebService1Soap)(this)).GetPiesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bewallwpf.WebServicePoxy.GetBarOrLinesResponse bewallwpf.WebServicePoxy.WebService1Soap.GetBarOrLines(bewallwpf.WebServicePoxy.GetBarOrLinesRequest request) {
            return base.Channel.GetBarOrLines(request);
        }
        
        public string GetBarOrLines() {
            bewallwpf.WebServicePoxy.GetBarOrLinesRequest inValue = new bewallwpf.WebServicePoxy.GetBarOrLinesRequest();
            inValue.Body = new bewallwpf.WebServicePoxy.GetBarOrLinesRequestBody();
            bewallwpf.WebServicePoxy.GetBarOrLinesResponse retVal = ((bewallwpf.WebServicePoxy.WebService1Soap)(this)).GetBarOrLines(inValue);
            return retVal.Body.GetBarOrLinesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bewallwpf.WebServicePoxy.GetBarOrLinesResponse> bewallwpf.WebServicePoxy.WebService1Soap.GetBarOrLinesAsync(bewallwpf.WebServicePoxy.GetBarOrLinesRequest request) {
            return base.Channel.GetBarOrLinesAsync(request);
        }
        
        public System.Threading.Tasks.Task<bewallwpf.WebServicePoxy.GetBarOrLinesResponse> GetBarOrLinesAsync() {
            bewallwpf.WebServicePoxy.GetBarOrLinesRequest inValue = new bewallwpf.WebServicePoxy.GetBarOrLinesRequest();
            inValue.Body = new bewallwpf.WebServicePoxy.GetBarOrLinesRequestBody();
            return ((bewallwpf.WebServicePoxy.WebService1Soap)(this)).GetBarOrLinesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bewallwpf.WebServicePoxy.GetAppInfoResponse bewallwpf.WebServicePoxy.WebService1Soap.GetAppInfo(bewallwpf.WebServicePoxy.GetAppInfoRequest request) {
            return base.Channel.GetAppInfo(request);
        }
        
        public string GetAppInfo() {
            bewallwpf.WebServicePoxy.GetAppInfoRequest inValue = new bewallwpf.WebServicePoxy.GetAppInfoRequest();
            inValue.Body = new bewallwpf.WebServicePoxy.GetAppInfoRequestBody();
            bewallwpf.WebServicePoxy.GetAppInfoResponse retVal = ((bewallwpf.WebServicePoxy.WebService1Soap)(this)).GetAppInfo(inValue);
            return retVal.Body.GetAppInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bewallwpf.WebServicePoxy.GetAppInfoResponse> bewallwpf.WebServicePoxy.WebService1Soap.GetAppInfoAsync(bewallwpf.WebServicePoxy.GetAppInfoRequest request) {
            return base.Channel.GetAppInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<bewallwpf.WebServicePoxy.GetAppInfoResponse> GetAppInfoAsync() {
            bewallwpf.WebServicePoxy.GetAppInfoRequest inValue = new bewallwpf.WebServicePoxy.GetAppInfoRequest();
            inValue.Body = new bewallwpf.WebServicePoxy.GetAppInfoRequestBody();
            return ((bewallwpf.WebServicePoxy.WebService1Soap)(this)).GetAppInfoAsync(inValue);
        }
    }
}
